### ISSUE TITLE
Rails 5 + Mongoid 6

### ISSUE THREAD

**Issue by pbougie** [chamnap/mongoid-observers#4]
Are there any plans to update this project for Rails 5 and Mongoid 6?
Thanks.

**Comment by chamnap** [comment]
The thing is that this gem depends on `rails-observers`, and `rails-observers` don't release new version that support rails 5.

**Comment by pbougie** [comment]
Unfortunate that they haven't updated their gem. However, the `master` branch of `rails-observers` does seem to support Rails 5.

**Comment by chamnap** [comment]
Yeah, the master branch of `rails-observers` does support rails 5. The thing is that I can't put it as dependency on the gemspec. The user needs to reference manually, in this case.

**Comment by pbougie** [comment]
Thanks for getting started on this. However, I'm running into some problems.

First, I tried it with:

``` ruby
gem 'mongoid-observers'
gem 'rails-observers', github: 'rails/rails-observers'
```

The app started successfully but when I made changes to a record, the observer ended up inserting hundreds of entries instead of one. It threw an `exception reentered` error in `ActiveSupport::Notifications::Instrumenter#instrument`.

My second attempt was with:

``` ruby
gem 'mongoid-observers', github: 'chamnap/mongoid-observers'
gem 'rails-observers', github: 'rails/rails-observers'
```

Unfortunately, the app doesn't even start. Here's the error:

``` ruby
~/app/.bundle/gems/ruby/2.3.0/bundler/gems/mongoid-observers-b5c5361e194a/lib/mongoid/observers/railtie.rb:22:in `block (2 levels) in <class:Railtie>': undefined method `to_prepare' for "expression":String (NoMethodError)
```

Both scenarios are running Rails 5.0.0.1. Hope this helps.

**Comment by chamnap** [comment]
@pbougie, you can try again with master branch. I'm fixing the builds now.

**Comment by chamnap** [comment]
Let's close this issue. I just released a new version. Let's me know if there is any problems.
