### ISSUE TITLE
Transfer mongoid-observers to github/mongoid?

### ISSUE THREAD

**Issue by Fudoshiki** [chamnap/mongoid-observers#5]
Hi, related simi/mongoid_paranoia#49
@chamnap what do you thing?

**Comment by dblock** [comment]
I think preserving these for posterity is better than not. Happy to take this gem. Transfer it to me and I'll move it into the mongoid org. Thanks!

**Comment by chamnap** [comment]
I totally agree for the sake of community. @dblock, I'll transfer to you now.

**Comment by chamnap** [comment]
@dblock, it's done.

**Comment by dblock** [comment]
Alright! It's now part of the @mongoid org. You are still admin on the repo, so you can add people and what not. Next steps is to change links in READMEs, etc. Also add the project to http://mongoid.github.io/ maybe?

**Comment by dblock** [comment]
Also, add me, @estolfo and @durran to gem owners!

See http://mongoid.github.io/misc/adding

**Comment by chamnap** [comment]
I'll do it this weekend, a bit busy recently.
